// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opmgrupbwdubxxvpsjng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbWdydXBid2R1Ynh4dnBzam5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODI3OTUsImV4cCI6MjA3MjY1ODc5NX0.MYCZyJHcrLpDLQ_rfjEhKstgPqyGkdYOKdrpHP3hFlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});